maven_group=fr.samlegamer.addonslib
mod_group_id=fr.samlegamer.addonslib
group=fr.samlegamer.addonslib

archives_base_name=addonslib
mod_id=addonslib
mod_name=AddonsLib

mod_license=All Rights Reserved
mod_authors=Samlegamer
mod_author=Samlegamer
mod_description=A library to facilitate registration between mods, in particular macaw's bridges/roofs/fences/etc...

mod_init=fr.samlegamer.addonslib.AddonsLibFabric

website_link=https://www.curseforge.com/minecraft/mc-mods/addonslib
issues_link=https://github.com/Samlegamer/AddonsLib

url_issues=https://github.com/Samlegamer/AddonsLib
url_project=https://www.curseforge.com/minecraft/mc-mods/addonslib

